apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp
data:
  demo: hej
  test: "to jest test!"
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: gcr.io/kuar-demo/kuard-amd64:1
    envFrom:
    - configMapRef:
        name: myapp

