apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp
data:
  demo: hej
  test: "to jest test!"
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: gcr.io/kuar-demo/kuard-amd64:1
    resources: {}
    env:
      - name: TEST2
        value: "TO jest DEMO"
      - name: DEMO
        value: "1.1.1.1"
      - name: DEMO2
        valueFrom:
          configMapKeyRef:
            name: myapp
            key: demo       
      - name: test
        valueFrom:
          configMapKeyRef:
            name: myapp
            key: test   