apiVersion: v1
kind: ConfigMap
metadata:
  name: kuard-config
data:
  test: "cludica"
  test2: "cludica jest super!"
---
# Deployment
# zaladowanie zmiennych srodowiskowych z kuard-config 
# 2 repliki
# image: gcr.io/kuar-demo/kuard-amd64:1
# Dodac livenessProbe i readinessProbe
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:1
        resources: {}
        envFrom:
          - configMapRef:
              name: kuard-config
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 15
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          failureThreshold: 3
          periodSeconds: 5
          initialDelaySeconds: 30
          successThreshold: 2