apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-multi-path-web
  labels:
    name: echo-multi-path-web
spec:
  ingressClassName: nginx
  rules:
  - host: api.127-0-0-1.nip.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: echo-v1
            port: 
              number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-multi-path-api
  labels:
    name: echo-multi-path-api
spec:
  ingressClassName: nginx
  rules:
  - host: api.127-0-0-1.nip.io
    http:
      paths:
      - pathType: Prefix
        path: "/api"
        backend:
          service:
            name: echo-v2
            port: 
              number: 8080