# Deployemnt, Service, Ingress web
# image lukaszkaluzny/k8s-canary-on-ingress:web
# port 80
# path: /
# hostname pets.127-0-0-1.nip.io
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: lukaszkaluzny/k8s-canary-on-ingress:web
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
---
# Deployemnt, Service, Ingress api
# image lukaszkaluzny/k8s-canary-on-ingress:cat
# port 8080
# path: /pet
# path: /gif
# hostname pets.127-0-0-1.nip.io
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: lukaszkaluzny/k8s-canary-on-ingress:cat
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app
  labels:
    name: app
spec:
  ingressClassName: nginx
  rules:
  - host: pets.127-0-0-1.nip.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: web
            port: 
              number: 80
      - pathType: Prefix
        path: "/pet"
        backend:
          service:
            name: api
            port: 
              number: 8080
      - pathType: Prefix
        path: "/gif"
        backend:
          service:
            name: api
            port: 
              number: 8080
